path=/data/visitor/ihmi1611/id16a/20260428/PROCESSED_DATA/SiemensStar/SiemensStar_pseudorandom_010nm_0001
path_out=/data/visitor/ihmi1611/id16a/20260428/PROCESSED_DATA/SiemensStar/SiemensStar_pseudorandom_010nm_0001/phasing

nx_file=projections/SiemensStar_pseudorandom_010nm_0001_scan0001.nx  # NXtomo input (relative to path)
h5_out=nfp_results.h5  # NFP output: probe, positions (relative to path_out)

nchunk=4              # projections per GPU batch
n=4096                # detector size (pixels)

niter=513             # number of NFP iterations
checkpoint_step=-1    # save checkpoint every N iters (-1 = disabled)
error_step=16         # print error every N iters

rho=1,2,0.1           # gradient step scales: object, probe, positions
log_level=INFO
